site_name: SwiftBar4s
site_description: Scala framework for creating swiftbar/bitbar applications
repo_name: 'bilal-fazlani/swiftbar4s'
repo_url: 'https://github.com/bilal-fazlani/swiftbar4s'
edit_uri: edit/main/docs/
strict: true

theme:
  features:
    - tabs
    - instant
    - toc.integrate
    - navigation.sections
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  favicon: 'images/favicon.ico'
  palette:
    scheme: preference 
  logo: 'images/logo-svg.svg'

# google_analytics:
#   - 'UA-39358317-3'
#   - 'auto'

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      linenums: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.escapeall:
      nbsp: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
     permalink: "#"   

plugins:
  - search
  - awesome-pages

# Customization
extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: 'https://github.com/bilal-fazlani'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/bilal_fazlani'
    - icon: fontawesome/brands/linkedin
      link: 'https://www.linkedin.com/in/bilal-fazlani/'